package com.keven.springDemo.mapper;

import com.keven.springDemo.model.Permission;
import com.keven.springDemo.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	long countByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int deleteByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	List<Permission> selectByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	Permission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int updateByPrimaryKey(Permission record);
}