package com.keven.springDemo.mapper;

import com.keven.springDemo.model.RolePermission;
import com.keven.springDemo.model.RolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int deleteByExample(RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int insert(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int insertSelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	List<RolePermission> selectByExample(RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int updateByExampleSelective(@Param("record") RolePermission record,
			@Param("example") RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_permission
	 * @mbg.generated  Tue Sep 24 20:46:08 CST 2019
	 */
	int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);
}