package com.keven.springDemo.model;

import java.io.Serializable;

public class RolePermission implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_permission.permission_id
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	private Integer permission_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_permission.role_id
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	private Integer role_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role_permission
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_permission.permission_id
	 * @return  the value of sys_role_permission.permission_id
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	public Integer getPermission_id() {
		return permission_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_permission.permission_id
	 * @param permission_id  the value for sys_role_permission.permission_id
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	public void setPermission_id(Integer permission_id) {
		this.permission_id = permission_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_permission.role_id
	 * @return  the value of sys_role_permission.role_id
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	public Integer getRole_id() {
		return role_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_permission.role_id
	 * @param role_id  the value for sys_role_permission.role_id
	 * @mbg.generated  Mon Oct 14 11:44:43 CST 2019
	 */
	public void setRole_id(Integer role_id) {
		this.role_id = role_id;
	}
}