package com.keven.shiro.model;

import java.io.Serializable;

public class Role implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.available
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private Boolean available;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.description
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
	 * @return  the value of sys_role.id
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
	 * @param id  the value for sys_role.id
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.available
	 * @return  the value of sys_role.available
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public Boolean getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.available
	 * @param available  the value for sys_role.available
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public void setAvailable(Boolean available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.description
	 * @return  the value of sys_role.description
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.description
	 * @param description  the value for sys_role.description
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role
	 * @return  the value of sys_role.role
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role
	 * @param role  the value for sys_role.role
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}
}