package com.keven.shiro.model;

import java.io.Serializable;

public class UserRole implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.uid
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.role_id
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user_role
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.uid
	 * @return  the value of sys_user_role.uid
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.uid
	 * @param uid  the value for sys_user_role.uid
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.role_id
	 * @return  the value of sys_user_role.role_id
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.role_id
	 * @param roleId  the value for sys_user_role.role_id
	 * @mbg.generated  Mon Oct 14 11:48:22 CST 2019
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}